# Generated by Django 4.1.5 on 2023-02-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_coursefeedback"),
    ]

    operations = []
