# Generated by Django 4.1.5 on 2023-02-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_data_migration"),
    ]

    operations = []
