# Generated by Django 3.2.15 on 2023-02-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_data_migration"),
    ]

    operations = []
